FROM ghcr.io/stertooy/gda-image:4.10-slim as build

ENV GAP_HOME=/opt/gap

# Prerequisites
RUN apt-get update && \
    apt-get install --yes --no-install-recommends     \
        4ti2                  `# 4ti2Interface`       \
        libboost-dev          `# NormalizInterface`   \
        libcurl4-gnutls-dev   `# curlInterface`       \
        libfplll-dev          `# float`               \
        libmpc-dev            `# float`               \
        libmpfi-dev           `# float`               \
        libmpfr-dev           `# float`               \
        libzmq3-dev           `# ZeroMQInterface`     \
        polymake              `# polymaking`          \
        singular              `# singular`         && \
    rm -rf /var/lib/apt/lists/*

# Download GAP packages
RUN cd ${GAP_HOME} && \
    rm -rf pkg && \
    make bootstrap-pkg-full && \
    rm packages*.tar.gz && \
    cd ${GAP_HOME}/pkg && \
    rm -rf                             \
        itc-1.5                        \
        PolymakeInterface-2019.06.01   \
        xgap-4.30

# Build GAP packages
RUN cd ${GAP_HOME}/pkg && \
    ../bin/BuildPackages.sh

# Squash
FROM scratch
COPY --from=build / /

CMD ["bash"]
