FROM ghcr.io/stertooy/gda-image:4.9-slim as build

ENV GAP_HOME=/opt/gap

# Prerequisites
RUN apt-get update && \
    apt-get install --yes --no-install-recommends     \
        4ti2                  `# 4ti2Interface`       \
        automake              `# NormalizInterface`   \
        lib32gcc-6-dev        `# ANUPQ`               \
        libboost-dev          `# NormalizInterface`   \
        libc6-dev-i386        `# ANUPQ`               \
        libcurl4-gnutls-dev   `# curlInterface`       \
        libfplll-dev          `# float`               \
        libmpc-dev            `# float`               \
        libmpfi-dev           `# float`               \
        libmpfr-dev           `# float`               \
        libzmq3-dev           `# ZeroMQInterface`     \
        polymake              `# polymaking`          \       
        singular              `# singular`         && \
    rm -rf /var/lib/apt/lists/*

# Download GAP packages
RUN cd ${GAP_HOME} && \
    rm -rf pkg && \
    make bootstrap-pkg-full && \
    rm packages*.tar.gz && \
    cd ${GAP_HOME}/pkg && \
    rm -rf                  \
        itc-1.5             \
        linboxing           \
        PolymakeInterface   \
        qaos-1.6            \
        xgap-4.27

# Build GAP packages
RUN cd ${GAP_HOME}/pkg && \
    ../bin/BuildPackages.sh

# Squash
FROM scratch
COPY --from=build / /

CMD ["bash"]
