FROM ghcr.io/stertooy/gda-image:4.9-slim as build

ENV GAP_HOME=/opt/gap

# Prerequisites
RUN apt-get update && \
    apt-get install --yes --no-install-recommends \
        4ti2                 `# 4ti2Interface` \
        automake             `# NormalizInterface` \
        lib32gcc-6-dev       `# ANUPQ` \
        libc6-dev-i386       `# ANUPQ` \
        libboost-dev         `# NormalizInterface` \
        libcurl4-gnutls-dev  `# curlInterface` \
        libfplll-dev         `# float` \
        libmpc-dev           `# float` \
        libmpfi-dev          `# float` \
        libmpfr-dev          `# float` \
        libncurses-dev       `# Browse` \
        libx11-dev           `# XGAP` \
        libxaw7-dev          `# XGAP` \
        libxt-dev            `# XGAP` \
        libzmq3-dev          `# ZeroMQInterface` \
        pari-gp              `# Alnuth` \
        polymake             `# polymaking` \
        singular             `# singular` && \
    rm -rf /var/lib/apt/lists/*

# Download GAP packages
RUN cd ${GAP_HOME} && \
    rm -rf pkg && \
    make bootstrap-pkg-full && \
    rm packages*.tar.gz && \
    cd ${GAP_HOME}/pkg && \
    rm -rf \
        linboxing \
        PolymakeInterface \
        qaos-*

# Build GAP packages
RUN cd ${GAP_HOME}/pkg && \
    ../bin/BuildPackages.sh

# Squash
FROM scratch
COPY --from=build / /

CMD ["bash"]
