FROM debian:bookworm-slim as build

ENV GAP_BRANCH=master
ENV GAP_HOME=/opt/gap
ENV GAP_ROOT=/tmp/gaproot

# Prerequisites
RUN apt-get update && \
    apt-get upgrade --yes && \
    apt-get install --yes --no-install-recommends   \
        autoconf                                    \
        build-essential                             \
        ca-certificates                             \
        git                                         \
        libgmp-dev                                  \
        libncurses-dev        `# Browse`            \
        libtool                                     \
        pari-gp               `# Alnuth`            \
        netbase               `# IO`                \
        wget                                        \
        zlib1g-dev                               && \
    rm -rf /var/lib/apt/lists/*

# Download and build GAP
RUN git clone --depth 1 --branch ${GAP_BRANCH} https://github.com/gap-system/gap ${GAP_HOME} && \
    cd ${GAP_HOME} && \
    rm -rf       \
        dev      \
        extern   \
        hpcgap

# Build GAP
RUN cd ${GAP_HOME} && \
    ./autogen.sh && \
    ./configure && \
    make

# Download GAP packages
RUN cd ${GAP_HOME} && \
    make bootstrap-pkg-full && \
    rm packages*.tar.gz && \
    cd ${GAP_HOME}/pkg && \
    rm -rf \
        4ti2interface   \
        ace   \
        agt   \
        anupq   \
        automata   \
        automgrp   \
        cap   \
        cddinterface   \
        circle   \
        classicpres   \
        cohomolo   \
        congruence   \
        corelg   \
        crime   \
        crypting   \
        cubefree   \
        curlinterface   \
        cvec   \
        datastructures   \
        deepthought   \
        design   \
        difsets   \
        digraphs   \
        edim   \
        example   \
        examplesforhomalg   \
        ferret   \
        fining   \
        float   \
        format   \
        fplsa   \
        fr   \
        francy   \
        fwtree   \
        gauss   \
        gaussforhomalg   \
        gbnp   \
        generalizedmorphismsforcap   \
        gradedmodules   \
        gradedringforhomalg   \
        grape   \
        groupoids   \
        grpconst   \
        guarana   \
        guava   \
        hap   \
        hapcryst   \
        hecke   \
        help   \
        homalg   \
        homalgtocas   \
        idrel   \
        images   \
        intpic   \
        io_forhomalg   \
        itc   \
        json   \
        jupyterkernel   \
        jupyterviz   \
        kan   \
        kbmag   \
        liealgdb   \
        liepring   \
        liering   \
        linearalgebraforcap   \
        localizeringforhomalg   \
        loops   \
        lpres   \
        majoranaalgebras   \
        mapclass   \
        matgrp   \
        matricesforhomalg   \
        modisom   \
        modulepresentationsforcap   \
        modules   \
        monoidalcategories   \
        nconvex   \
        nilmat   \
        nock   \
        normalizinterface   \
        nq   \
        numericalsgps   \
        openmath   \
        packagemanager   \
        patternclass   \
        permut   \
        polymaking   \
        qpa   \
        quagroup   \
        rcwa   \
        rds   \
        repndecomp   \
        repsn   \
        ringsforhomalg   \
        sco   \
        scscp   \
        semigroups   \
        sglppow   \
        sgpviz   \
        simpcomp   \
        singular   \
        sla   \
        smallsemi   \
        sonata   \
        symbcompcc   \
        thelma   \
        toolsforhomalg   \
        toric   \
        toricvarieties   \
        ugaly   \
        unipot   \
        unitlib   \
        uuid   \
        walrus   \
        wedderga   \
        xgap   \
        xmod   \
        xmodalg   \
        yangbaxter   \
        zeromqinterface

# Build GAP packages
RUN cd ${GAP_HOME}/pkg && \
    ../bin/BuildPackages.sh

# Prepare for Github Actions use
RUN mkdir -p /tmp/gaproot/pkg && \
    printf '#!/bin/sh\nLC_CTYPE=C.UTF-8 TERM="xterm" %s/bin/gap.sh -l "%s;" --quitonbreak "$@"\n' ${GAP_HOME} ${GAP_ROOT} > /usr/local/bin/gap && \
    chmod +x /usr/local/bin/gap

# Squash
FROM scratch
COPY --from=build / /

CMD ["bash"]
