name: Publish GAP Docker image

on:
  workflow_dispatch:
    inputs:
      BRANCH:
        required: true
        type: choice
        options:
          - "master"
          - "4.11"
          - "4.10"
          - "4.9"
      TYPE:
        required: true
        type: choice
        options:
          - "full"
          - "slim"
  workflow_call:
    inputs:
      BRANCH:
        required: true
        type: string
      TYPE:
        required: true
        type: string

env:
  REGISTRY: ghcr.io

jobs:
  build:
    name: Publish GAP-${{ inputs.BRANCH }} Docker image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Compose Dockerfile
        shell: bash
        run: |
          mv slim/Dockerfile Dockerfile
          
          # Add image name to Dockerfile
          IMAGE=$(grep "${{ inputs.branch }}" ${{ inputs.type }}/images.txt | cut -d'=' -f2)
          sed -i -e "s#{{IMAGE}}#$IMAGE#" Dockerfile
          
          # Add GAP branch name to Dockerfile
          BRANCH=$(sed '/master/!s/^/stable-&/' <<< "${{ inputs.branch }}")
          sed -i -e "s/{{BRANCH}}/$BRANCH/" Dockerfile
          
          # Add dependencies to Dockerfile
          DEPENDENCIES=$(tr "\n" " " < ${{ inputs.type }}/dependencies/${{ inputs.branch }}.txt)
          sed -i -e "s/{{DEPENDENCIES}}/$DEPENDENCIES/" Dockerfile
          
          # Add packages to Dockerfile
          PACKAGES=$(tr "\n" " " < ${{ inputs.type }}/packages.txt)
          sed -i -e "s/{{PACKAGES}}/$PACKAGES/" Dockerfile
          
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ${{ github.repository }}
            ${{ env.REGISTRY }}/${{ github.repository }}
          tags: |
            type=raw,value=${{ inputs.BRANCH }}${{ inputs.TYPE == 'slim' && '-slim' || '' }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
