name: Publish GAP Docker image

on:
  workflow_dispatch:
    inputs:
      BRANCH:
        required: true
        type: choice
        options:
          - "master"
          - "4.11"
          - "4.10"
          - "4.9"
      TYPE:
        required: true
        type: choice
        options:
          - "full"
          - "slim"
  workflow_call:
    inputs:
      BRANCH:
        required: true
        type: string
      TYPE:
        required: true
        type: string

env:
  REGISTRY: ghcr.io

jobs:
  build:
    name: Publish GAP-${{ inputs.BRANCH }} Docker image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Compose Dockerfile
        shell: bash
        run: |
          mv slim/Dockerfile Dockerfile
          PACKAGES=$(tr "\n" " " < ${{ inputs.type }}/packages.txt)
          DEPENDENCIES=$(tr "\n" " " < ${{ inputs.type }}/dependencies/${{ inputs.branch }}.txt)
          IMAGE=$(grep "{{ inputs.branch}}" images | cut -d'=' -f2)
          BRANCH=$(sed '/master/!s/^/stable-&/' <<< "${{ inputs.branch }}")
          sed -i -e "s/{{IMAGE}}/$IMAGE/" Dockerfile
          sed -i -e "s/{{BRANCH}}/$BRANCH/" Dockerfile
          sed -i -e "s/{{PACKAGES}}/$PACKAGES/" -e Dockerfile
          sed -i -e "s/{{DEPENDENCIES}}/$DEPENDENCIES/" Dockerfile
          
      #- name: Log in to Docker Hub
      #  uses: docker/login-action@v2
      #  with:
      #    username: ${{ github.repository_owner }}
      #    password: ${{ secrets.DOCKER_TOKEN }}

      #- name: Log in to GitHub Container Registry
      #  uses: docker/login-action@v2
      #  with:
      #    registry: ${{ env.REGISTRY }}
      #    username: ${{ github.actor }}
      #    password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ${{ github.repository }}
            ${{ env.REGISTRY }}/${{ github.repository }}
          tags: |
            type=raw,value=test
          # type=raw,value=${{ inputs.BRANCH }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
