name: Publish GAP Docker image

on:
  workflow_dispatch:
    inputs:
      BRANCH:
        required: true
        type: choice
        options:
          - "master"
          - "master-slim"
          - "4.11"
          - "4.11-slim"
          - "4.10"
          - "4.10-slim"
          - "4.9"
          - "4.9-slim"
          - "tex"
          - "tex-slim"
  workflow_call:
    inputs:
      BRANCH:
        required: true
        type: string

env:
  REGISTRY: ghcr.io

jobs:
  build:
    name: Publish GAP-${{ inputs.BRANCH }} Docker image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Compose Dockerfile
        shell: bash
        run: |
          mv slim/Dockerfile Dockerfile
          PACKAGES=$(tr "\n" " " < slim/packages.txt)
          IMAGE="debian:stretch-slim"
          BRANCH="stable-4.9"
          sed "s/{{IMAGE}}/$IMAGE/" Dockerfile
          sed "s/{{BRANCH}}/$BRANCH/" Dockerfile
          sed "s/{{PKGS}}/$PACKAGES/" Dockerfile
          
      #- name: Log in to Docker Hub
      #  uses: docker/login-action@v2
      #  with:
      #    username: ${{ github.repository_owner }}
      #    password: ${{ secrets.DOCKER_TOKEN }}

      #- name: Log in to GitHub Container Registry
      #  uses: docker/login-action@v2
      #  with:
      #    registry: ${{ env.REGISTRY }}
      #    username: ${{ github.actor }}
      #    password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ${{ github.repository }}
            ${{ env.REGISTRY }}/${{ github.repository }}
          tags: |
            type=raw,value=test
          # type=raw,value=${{ inputs.BRANCH }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
