name: "Publish GAP-stable-full Docker images (scheduled)"

on:
  workflow_dispatch:
  schedule:
    - cron: '37 5 7 * *'

jobs:
  GAP-4-13-full:
    uses: stertooy/gda-image/.github/workflows/publish-image.yml@main
    secrets: inherit
    with:
      BRANCH: "4.13"
      TYPE: "full"
      
  GAP-4-12-full:
    uses: stertooy/gda-image/.github/workflows/publish-image.yml@main
    secrets: inherit
    with:
      BRANCH: "4.12"
      TYPE: "full"

  GAP-4-11-full:
    uses: stertooy/gda-image/.github/workflows/publish-image.yml@main
    secrets: inherit
    with:
      BRANCH: "4.11"
      TYPE: "full"
      
  GAP-4-10-full:
    uses: stertooy/gda-image/.github/workflows/publish-image.yml@main
    secrets: inherit
    with:
      BRANCH: "4.10"
      TYPE: "full"
      
  GAP-4-9-full:
    uses: stertooy/gda-image/.github/workflows/publish-image.yml@main
    secrets: inherit
    with:
      BRANCH: "4.9"
      TYPE: "full"
