name: "Publish GAP-master-min Docker images (scheduled)"

on:
  workflow_dispatch:
  schedule:
    - cron: '37 3 * * 6'

jobs:
  GAP-master-min:
    uses: stertooy/gda-image/.github/workflows/publish-image.yml@main
    secrets: inherit
    with:
      BRANCH: "master"
      TYPE: "min"
      
  GAP-tex-min:
    uses: stertooy/gda-image/.github/workflows/publish-image.yml@main
    secrets: inherit
    with:
      BRANCH: "tex"
      TYPE: "min"
