name: "Publish GAP-stable-slim Docker images (scheduled)"

on:
  schedule:
    - cron: '5/10 * * * *'

jobs:
  GAP-4-11-slim:
    name: "Publish GAP-4.11-slim Docker image (scheduled)"
    uses: stertooy/gda-image/.github/workflows/publish-image.yml@main
    secrets: inherit
    with:
      BRANCH: "4.11"
      TYPE: "slim"
      
  GAP-4-10-slim:
    name: "Publish GAP-4.10-slim Docker image (scheduled)"
    uses: stertooy/gda-image/.github/workflows/publish-image.yml@main
    secrets: inherit
    with:
      BRANCH: "4.10"
      TYPE: "slim"
      
  GAP-4-9-slim:
    name: "Publish GAP-4.9-slim Docker image (scheduled)"
    uses: stertooy/gda-image/.github/workflows/publish-image.yml@main
    secrets: inherit
    with:
      BRANCH: "4.9"
      TYPE: "slim"
