name: "Publish GAP-stable-full Docker images (scheduled)"

on:
  schedule:
    - cron: '37 5 7 * *'

jobs:
  GAP-4-11-slim:
    uses: stertooy/gda-image/.github/workflows/publish-image.yml@main
    secrets: inherit
    with:
      BRANCH: "4.11"
      TYPE: "full"
      
  GAP-4-10-slim:
    uses: stertooy/gda-image/.github/workflows/publish-image.yml@main
    secrets: inherit
    with:
      BRANCH: "4.10"
      TYPE: "full"
      
  GAP-4-9-slim:
    uses: stertooy/gda-image/.github/workflows/publish-image.yml@main
    secrets: inherit
    with:
      BRANCH: "4.9"
      TYPE: "full"
