name: "Publish GAP-stable-min Docker images (scheduled)"

on:
  workflow_dispatch:
  schedule:
    - cron: '37 3 7 * *'

jobs:
  GAP-4-13-min:
    uses: stertooy/gda-image/.github/workflows/publish-image.yml@main
    secrets: inherit
    with:
      BRANCH: "4.13"
      TYPE: "min"

  GAP-4-12-min:
    uses: stertooy/gda-image/.github/workflows/publish-image.yml@main
    secrets: inherit
    with:
      BRANCH: "4.12"
      TYPE: "min"

  GAP-4-11-min:
    uses: stertooy/gda-image/.github/workflows/publish-image.yml@main
    secrets: inherit
    with:
      BRANCH: "4.11"
      TYPE: "min"
      
  GAP-4-10-min:
    uses: stertooy/gda-image/.github/workflows/publish-image.yml@main
    secrets: inherit
    with:
      BRANCH: "4.10"
      TYPE: "min"
      
  GAP-4-9-min:
    uses: stertooy/gda-image/.github/workflows/publish-image.yml@main
    secrets: inherit
    with:
      BRANCH: "4.9"
      TYPE: "min"
