name: "Publish GAP Docker images using master branch (scheduled)"

on:
  workflow_dispatch:
  schedule:
    - cron: '37 5 * * 6'

jobs:
  GAP-master:
    strategy:
      matrix:
        VERSION: ["master","tex"]
        TYPE: ["min","slim","full"]
    uses: stertooy/gda-image/.github/workflows/publish-image.yml@main
    secrets: inherit
    with:
      BRANCH: "master"
      TYPE: "full"
