name: "Publish GAP Docker images using stable releases (scheduled)"

on:
  workflow_call:
  workflow_dispatch:
  schedule:
    - cron: '37 5 * * 6'
jobs:
  GAP-stable:
    strategy:
      fail-fast: false
      matrix:
        VERSION: ["4.12.0","4.12.1","4.12.2","4.13.0","4.13.1","4.14.0","4.15.0","4.15.1"]
        TYPE: ["slim","full"]
    uses: stertooy/gda-image/.github/workflows/publish-image.yml@main
    secrets: inherit
    with:
      VERSION: ${{ matrix.VERSION }}
      TYPE: ${{ matrix.TYPE }}
